config/routes.rb
Thejqueryist::Application.routes.draw do
  resources :todos
  root 'todos#index'

  

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      format.html do
        if @todo.save
          flash[:notice] = "Todo has been created"
          redirect_to @todo
        else
          flash[:alert] = "Todo has not been created"
          render :action => "new"
        end
      end
      format.js do
        unless @todo.save
          render text: @todo.errors.full_message.join,
            status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      format.html do
        if @todo.update(todo_params)
          flash[:notice] = "Todo has been updated"
          redirect_to @todo
        else
          flash[:alert] = "Todo has not been update"
          render :action => "edit"
        end
      end
      format.js do
        unless @todo.update(todo_params)
          render text: @todo.errors.full_message.join,
            status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:description, :done, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thejqueryist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo, remote: true) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<tr id='<%= todo.id %>'>
        <td><%= todo.description %></td>
        <td><%= todo.done %></td>
        <td><%= todo.due %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), remote: true %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/todos/create.js.erb
$('#new_todo').remove();
$('#new_link').show();
$('tbody').append('<%= j render(@todo) %>');

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/edit.js.erb
$('#<%= @todo.id %>').hide().after('<%= j render("form") %>')

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Done</th>
      <th>Due</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr id='<%= todo.id %>'>
        <td><%= todo.description %></td>
        <td><%= todo.done %></td>
        <td><%= todo.due %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), remote: true %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path,remote: true, id: :new_link%>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @todo.done %>
</p>

<p>
  <strong>Due:</strong>
  <%= @todo.due %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/todos/update.js.erb
$('#edit_todo_<%= @todo.id %>').remove();
$('#<%= @todo.id %>').replaceWith('<%= j render(@todo) %>');